// Package inventory provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package inventory

// Defines values for ClusterFeaturesDrsMode.
const (
	FullyAutomated     ClusterFeaturesDrsMode = "Fully Automated"
	Manual             ClusterFeaturesDrsMode = "Manual"
	None               ClusterFeaturesDrsMode = "None"
	PartiallyAutomated ClusterFeaturesDrsMode = "Partially Automated"
)

// Valid indicates whether the value is a known member of the ClusterFeaturesDrsMode enum.
func (e ClusterFeaturesDrsMode) Valid() bool {
	switch e {
	case FullyAutomated:
		return true
	case Manual:
		return true
	case None:
		return true
	case PartiallyAutomated:
		return true
	default:
		return false
	}
}

// Defines values for NetworkType.
const (
	Distributed NetworkType = "Distributed"
	Standard    NetworkType = "Standard"
)

// Valid indicates whether the value is a known member of the NetworkType enum.
func (e NetworkType) Valid() bool {
	switch e {
	case Distributed:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// ClusterFeatures defines model for ClusterFeatures.
type ClusterFeatures struct {
	// DrsEnabled Whether DRS (Distributed Resource Scheduler) is enabled for this cluster
	DrsEnabled *bool `json:"drsEnabled,omitempty"`

	// DrsMode DRS automation mode for the cluster
	DrsMode *ClusterFeaturesDrsMode `json:"drsMode,omitempty"`

	// StorageDrsEnabled Whether Storage DRS is enabled for this cluster
	StorageDrsEnabled *bool `json:"storageDrsEnabled,omitempty"`
}

// ClusterFeaturesDrsMode DRS automation mode for the cluster
type ClusterFeaturesDrsMode string

// ClusterUtilization defines model for ClusterUtilization.
type ClusterUtilization struct {
	// Confidence Data coverage confidence percentage (0-100), calculated as vCPU-weighted coverage
	Confidence float64 `json:"confidence"`

	// CpuAvg Average CPU utilization percentage (0-100)
	CpuAvg float64 `json:"cpu_avg"`

	// CpuMax Maximum CPU utilization percentage (0-100)
	CpuMax float64 `json:"cpu_max"`

	// CpuP95 95th percentile CPU utilization percentage (0-100)
	CpuP95 float64 `json:"cpu_p95"`

	// MemAvg Average memory utilization percentage (0-100)
	MemAvg float64 `json:"mem_avg"`

	// MemMax Maximum memory utilization percentage (0-100)
	MemMax float64 `json:"mem_max"`

	// MemP95 95th percentile memory utilization percentage (0-100)
	MemP95 float64 `json:"mem_p95"`
}

// Datastore defines model for Datastore.
type Datastore struct {
	DiskId                  string `json:"diskId"`
	FreeCapacityGB          int    `json:"freeCapacityGB"`
	HardwareAcceleratedMove bool   `json:"hardwareAcceleratedMove"`

	// HostId Identifier of the host where this datastore is attached
	HostId          *string `json:"hostId,omitempty"`
	Model           string  `json:"model"`
	ProtocolType    string  `json:"protocolType"`
	TotalCapacityGB int     `json:"totalCapacityGB"`
	Type            string  `json:"type"`
	Vendor          string  `json:"vendor"`
}

// DiskSizeTierSummary defines model for DiskSizeTierSummary.
type DiskSizeTierSummary struct {
	// TotalSizeTB Total disk size in TB for this tier
	TotalSizeTB float64 `json:"totalSizeTB"`

	// VmCount Number of VMs in this tier
	VmCount int `json:"vmCount"`
}

// DiskTypeSummary defines model for DiskTypeSummary.
type DiskTypeSummary struct {
	// TotalSizeTB Total disk size in TB for this disk type
	TotalSizeTB float64 `json:"totalSizeTB"`

	// VmCount Number of VMs that have at least one disk of this type
	VmCount int `json:"vmCount"`
}

// Host defines model for Host.
type Host struct {
	// CpuCores Number of CPU cores
	CpuCores *int `json:"cpuCores,omitempty"`

	// CpuSockets Number of CPU sockets
	CpuSockets *int `json:"cpuSockets,omitempty"`

	// Id Unique identifier for this host
	Id *string `json:"id,omitempty"`

	// MemoryMB Host memory in MB
	MemoryMB *int64 `json:"memoryMB,omitempty"`
	Model    string `json:"model"`
	Vendor   string `json:"vendor"`
}

// Infra defines model for Infra.
type Infra struct {
	ClustersPerDatacenter *[]int `json:"clustersPerDatacenter,omitempty"`

	// CpuOverCommitment CPU Overcommitment Ratio. Calculated as total Allocated vCPUs / Total Physical Cores
	CpuOverCommitment *float64       `json:"cpuOverCommitment,omitempty"`
	Datastores        []Datastore    `json:"datastores"`
	HostPowerStates   map[string]int `json:"hostPowerStates"`
	Hosts             *[]Host        `json:"hosts,omitempty"`

	// MemoryOverCommitment RAM memory Overcommitment Ratio. Calculated as total Allocated memory / Total memory available
	MemoryOverCommitment *float64  `json:"memoryOverCommitment,omitempty"`
	Networks             []Network `json:"networks"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	TotalClusters    *int `json:"totalClusters,omitempty"`
	TotalDatacenters *int `json:"totalDatacenters,omitempty"`
	TotalHosts       int  `json:"totalHosts"`
}

// Inventory defines model for Inventory.
type Inventory struct {
	// Clusters Map of cluster names to their inventory data
	Clusters map[string]InventoryData `json:"clusters"`
	Vcenter  *InventoryData           `json:"vcenter,omitempty"`

	// VcenterId ID of the vCenter
	VcenterId string `json:"vcenter_id"`

	// VcenterVersion Version of the vCenter api. For example "8.0.3.0"
	VcenterVersion *string `json:"vcenter_version,omitempty"`
}

// InventoryData defines model for InventoryData.
type InventoryData struct {
	ClusterFeatures    *ClusterFeatures    `json:"clusterFeatures,omitempty"`
	ClusterUtilization *ClusterUtilization `json:"clusterUtilization,omitempty"`
	Infra              Infra               `json:"infra"`
	Vcenter            *VCenter            `json:"vcenter,omitempty"`
	Vms                VMs                 `json:"vms"`
}

// MigrationIssue defines model for MigrationIssue.
type MigrationIssue struct {
	Assessment string  `json:"assessment"`
	Count      int     `json:"count"`
	Id         *string `json:"id,omitempty"`
	Label      string  `json:"label"`
}

// Network defines model for Network.
type Network struct {
	Dvswitch *string     `json:"dvswitch,omitempty"`
	Name     string      `json:"name"`
	Type     NetworkType `json:"type"`
	VlanId   *string     `json:"vlanId,omitempty"`
	VmsCount *int        `json:"vmsCount,omitempty"`
}

// NetworkType defines model for Network.Type.
type NetworkType string

// OsInfo defines model for OsInfo.
type OsInfo struct {
	Count     int  `json:"count"`
	Supported bool `json:"supported"`

	// UpgradeRecommendation Recommended OS upgrade for MTV unsupported OS that can be upgraded to a supported OS
	UpgradeRecommendation *string `json:"upgradeRecommendation,omitempty"`
}

// VCenter defines model for VCenter.
type VCenter struct {
	Id string `json:"id"`
}

// VMResourceBreakdown defines model for VMResourceBreakdown.
type VMResourceBreakdown struct {
	Total                          int `json:"total"`
	TotalForMigratable             int `json:"totalForMigratable"`
	TotalForMigratableWithWarnings int `json:"totalForMigratableWithWarnings"`
	TotalForNotMigratable          int `json:"totalForNotMigratable"`
}

// VMs defines model for VMs.
type VMs struct {
	// ComplexityDistribution Distribution of VMs by migration complexity level, enriched with total disk size per level. Supersedes distributionByComplexity.
	ComplexityDistribution *map[string]DiskSizeTierSummary `json:"complexityDistribution,omitempty"`
	CpuCores               VMResourceBreakdown             `json:"cpuCores"`

	// DiskComplexityTier Distribution of VMs across disk-complexity tiers used by the estimation engine (0-10TiB, 10-20TiB, 20-50TiB, 50+TiB).
	DiskComplexityTier *map[string]DiskSizeTierSummary `json:"diskComplexityTier,omitempty"`
	DiskCount          VMResourceBreakdown             `json:"diskCount"`
	DiskGB             VMResourceBreakdown             `json:"diskGB"`
	DiskSizeTier       *map[string]DiskSizeTierSummary `json:"diskSizeTier,omitempty"`
	DiskTypes          *map[string]DiskTypeSummary     `json:"diskTypes,omitempty"`

	// DistributionByComplexity Distribution of VMs by migration complexity level (0=Unsupported, 1=Easy, 2=Medium, 3=Hard, 4=WhiteGlove)
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	DistributionByComplexity *map[string]int `json:"distributionByComplexity,omitempty"`

	// DistributionByCpuTier Distribution of VMs across CPU tier buckets (e.g., "0-4", "5-8", "9-16", "17-32", "32+")
	DistributionByCpuTier *map[string]int `json:"distributionByCpuTier,omitempty"`

	// DistributionByMemoryTier Distribution of VMs across Memory tier buckets (e.g., "0-4", "5-16", "17-32", "33-64", "65-128", "129-256", "256+")
	DistributionByMemoryTier *map[string]int `json:"distributionByMemoryTier,omitempty"`

	// DistributionByNicCount Distribution of VMs by NIC count (e.g., "0", "1", "2", "3", "4+")
	DistributionByNicCount      *map[string]int      `json:"distributionByNicCount,omitempty"`
	MigrationWarnings           []MigrationIssue     `json:"migrationWarnings"`
	NicCount                    *VMResourceBreakdown `json:"nicCount,omitempty"`
	NotMigratableReasons        []MigrationIssue     `json:"notMigratableReasons"`
	OsInfo                      *map[string]OsInfo   `json:"osInfo,omitempty"`
	PowerStates                 map[string]int       `json:"powerStates"`
	RamGB                       VMResourceBreakdown  `json:"ramGB"`
	Total                       int                  `json:"total"`
	TotalMigratable             int                  `json:"totalMigratable"`
	TotalMigratableWithWarnings *int                 `json:"totalMigratableWithWarnings,omitempty"`
	TotalWithSharedDisks        *int                 `json:"totalWithSharedDisks,omitempty"`
}
