// Package inventory provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package inventory

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFndc9s2Ev9XMLh7SKaULMtxrtGMH2wlaTRzcjyW7TzUnQ5ErkWcSYAFQCpKx//7DT74YRKUZFftkyly",
	"sbu//V74TxzyNOMMmJJ48ieWYQwpMY/TJJcKxGcgKhdgXmWCZyAUtb8iIT8xskwgMr9AhoJminKGJ/hb",
	"DCoGgT5eL9Cbj1QqQZe5gghdg+S5CAEtwhiiPAHxFlGJwDJCD1wgFVOJQisdB1htMsATvOQ8AcLwU6AF",
	"z3kEXalaGskVT4l+gVIegeMIDYbA8hRPfsWf8yTZoHNLDxEO8BURipL22zlhOUlwgC85A/xbpZEGxVZa",
	"Iam4ICv4uIdBFpbUGOZluJ+qV3z5PwiVFux8dKtoQn8QK6rtppCzBxoBC30GI4qgkBdgdKopUQYiBKb0",
	"2zejwfFo9DZAIUnCPNFGQUSiYnp1O1gDXcX6RckDB/iBi5QoPMERz5cJ1EhYni5BaLXDLP+dFKuuPudO",
	"k+nVLcprUB519heUku9dQXPynaZ5elBB2YfTrqAPpyouudLkcMhSSLebMIWUi83BZG214oFl7WXIg8l8",
	"CrCAP3IqdNr+WsVm7dM6jGqz14rW5gmaqfabJ1t1tulSAZ5aSuXjzJSNTnF5EABTkpGQqs0vFw0SyhSs",
	"rNViIqI1EXAehpCA0Dk65wU0iBvlM+ZSzTwlahZp0z5QEIg/mJqpKdE6BgG2OEUlAF26iFJE13DsKYi6",
	"8iZeNJngioc8uTEfPASKK5Lswqv6ThfAIi48n1pedvZ2nLpSO2bvt3EltITdAumNBCofF/QH3FAQizxN",
	"idh0Y8LoZKguus660R+RhoEk/QGIMnRzUbcRRU0P2SPhinTKc6a6Ei4NiQ6Fu7nU/JuM2y5pmbdkGjwD",
	"0WcJbaa/xQrmg/Pw4UyhYqJQTApARKEEiFSIM7DCTOJoM7mwOpSZvnCpPK09y6fczWZ9GuuGExqiwJNI",
	"YZYvePgIaicP6ch8XKinmtwy+kcOiNZFpXKLLiveqmFK+tzjZw2/rPiUoflF06GUqffvvHr1l6F960Qr",
	"tX2umbEHQTy+saOZvAKh675uTGAEUgWp3FbWMBGCbJx3vhYgpjxNqUrBF5raNZomrGjQte6GQzR9Nq6Z",
	"AEPnScJD80qPbxIdIZtBV/FG0pAkaOoiZY9sqZqBfIbq3wIe8AT/66heLI7cVnFUN0APWB0VV3wNYqGI",
	"skxJFFGNkyRXz2tCn+Vqr2hu+ytm0sujkw25XT64Pp+XwfkaV7ijpS/cT1IQmhBr+z28wUCtuXjcH/Kl",
	"PeBDbZuhi18LNxNglMUTJXLw5Zo5VEd6n5801ZfSNzvKY4O4Gx7PArCB35+iBTDFfe0lbMDsC7dtZqxY",
	"a+gmLVoTcqYLqJOCGElBB4CerqhAtDxsJivs0byo68aLtHDnfvdV5tnHcr4rppa7pxaXDAoQ0q2Vz7nc",
	"2Q8tVohkdIg+c4HgO0mzBNA9/nk4Gp4MR/e4K6ddbWutg9ozWz1qAPd5tXl3sc187auOp0p6a7Peg0nz",
	"hG6NZXfY7j5NtL+775zfzMyyE93dXHomD500Vjmffed0JQyGmZS5Z18hUoKUZTnsRE9YzlF9s0LnREKW",
	"3lbd0tuSBU35pTQfjLLIdfetQq6pCmOvLjpL/buJWzvKG6SFIiwiQkdr447Le0VUJIT1LHhFKqd99mrB",
	"N5o57j68X+WMPXDfHVCvP2SeZVwoiPzLYp6tBIngGnRXAxZVqdBqgeV3iNDXBXKnzMg3v7lDOavE6M9m",
	"gg4JQ0soSSNdFQlqku0sF6EbnmsIPpuUydIxijcSWyJoD895eY95IYA8RnzNejaXLW3wMxc2zUyX35Pu",
	"G1XxNyIYZSu5/cwlV9vZ+7ot9uq2U5E+qX7bSV+A6mbxnapNlUguzl7TlH3rdac1NwWVq91yg9Ky8qFa",
	"J5RAAUmAgAkaxhChNVWxm+Pq5TMDYQmHaJFnICREYHbQSszFZlrxHPrafXOh217Su/GnAVL5WEvQ6P9x",
	"C5JQcGk370HDgIqCkCiXEGkb64EBpKLunh7YijJ3Z3dDLwJ0PBqM7dN4NDi1T6ejn27oxVuv2SxuV+Je",
	"aTd71fTKw6WpDmxuL9CbTQbyrwhqXrf0CPFG7Ms2su7O8BfTD70Znd3WfSRAx2efiNwEaHw2h4jmaYBO",
	"zr4QEQXo3dm3mCr4JeEFvMW7IWb5Luf58O2ZCnpD1+GPlrm5QUFvYLgaBugejwbv7rF+OB38bB8+DI7f",
	"26fj/wxOxvbxZPzTPd4Dxtwsjn8jEitgNxgfhpPBe/f9/engeOzwHo8/DManjnx8+n4/oJc0rLL9kDCX",
	"G3Q5myIzVjSAOVWdkg6P/fOuT+EqjJu9eq+9vDV5e9Zz1oD/inrFmh36Gojk7JDa8WoEfU19cgOsryxl",
	"B7sbEiR9dbXfNdTtNdG9eJzTZIuYCIh0AZcvneaejXLVjFEaotk/q1743N6+gO6JpO7I92TXYN7dGiyk",
	"1jWI+bd9Is3uUHeDLCFMy8UBTmgITBr72k0Nn2ckjAGNhyMc4FwkeIJjpTI5OTpar9dDYj4PuVgdubPy",
	"6L+z6afLxafBeDgaxipNjKmp0m6rl190paWCQNV1Azq/mpn/+LhbEVwcm6DPgJGM4gk+GY6Gx9p6RMXa",
	"T09P/w8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
